[[section-design-decisions]]
== Decisiones de DIseño

=== Tecnología
* NodeJS y Angular

El usar estas tecnologías fue una decisión muy difícil para el equipo ya que 
nunca las habiamos usado previamente en la carrera y nos va a suponer una dificultad añadida
el tener que familiarizarnos con estos frameworks.

Los escogimos porque dentro de las opciones disponibles (Angular o React) para hacer aplicaciones con Solid, 
Angular nos parecio la más adecuada para este proyecto en concreto. Además Angular tiene buena documentación y 
varios proyectos de ejemplo con todos los pasos para aprender como funciona rapidamente.


* TypeScript

Este lenguaje es el más usado con Angular para el desarrollo de aplicaciones. Tenemos ligeros conocimientos
de este lenguaje (basicamente, es un JavaScript con comprobación estática de tipos).

Tenemos conocimientos de JavaScript ya que lo habiamos dado en una asignatura previamente pero aun así nos supondra
más trabajo el aprender todo lo que puede ofrecer este lenguaje.


* SPARQL

Para obtener informacion de los PODS y enviar información a los mismos es necesario usar este lenguaje estandarizado para 
consulta de grafos. La sintaxis es muy similar a otros lenguajes de bases de datos pero el no tener muchos conocimientos de
como funciona internamente los PODS de Solid va a hacer que usar este lenguaje suponga otro reto más para el equipo.

