[[section-design-decisions]]
== Decisiones de Diseño

=== Tecnología
* NodeJS y Angular

El usar estas tecnologías fue una decisión muy difícil para el equipo ya que 
nunca las habiamos usado previamente en la carrera y nos va a suponer una dificultad añadida
el tener que familiarizarnos con estos frameworks.

Los escogimos porque dentro de las opciones disponibles (Angular o React) para hacer aplicaciones con Solid, 
Angular nos parecio la más adecuada para este proyecto en concreto. Además Angular tiene buena documentación y 
varios proyectos de ejemplo con todos los pasos para aprender como funciona rapidamente.


* TypeScript

Este lenguaje es el más usado con Angular para el desarrollo de aplicaciones. Tenemos ligeros conocimientos
de este lenguaje (basicamente, es un JavaScript con comprobación estática de tipos).

Tenemos conocimientos de JavaScript ya que lo habiamos dado en una asignatura previamente pero aun así nos supondra
más trabajo el aprender todo lo que puede ofrecer este lenguaje.


* SPARQL

Para obtener informacion de los PODS y enviar información a los mismos es necesario usar este lenguaje estandarizado para 
consulta de grafos. La sintaxis es muy similar a otros lenguajes de bases de datos pero el no tener muchos conocimientos de
como funciona internamente los PODS de Solid va a hacer que usar este lenguaje suponga otro reto más para el equipo.

=== Arquitectonicas
* Patrones

Aun estamos aprendiendo a utilizar las tecnologías mencionadas en el anterior apartado aun no sabemos con certeza los patrones 
que vamos a emplear en el diseño del código para poder mejorar el rendimiento de nuestra aplicación y hacer que sea mantenible y
ampliable.


=== Prioridades
* Funcionalidad

Hemos decidido basar nuestros esfuerzos en la fase de código en hacer que la aplicación sea funcional aunque la misma sea muy básisca.
Nuestro razonamiento para ello es que cuanto antes consigamos mandar información entre PODS (mensaje de texto entre dos usuarios)
antes podemos ampliar la aplicación con funcionalidad más compleja (mandar imágenes, chats grupales, etc..).

* Interfaz de usuarios

Cuando completemos la anterior prioridad nos centraremos en hacer una interfaz de usuario amigable, fácil de usar y sencilla.

* Disponibilidad

Procuraremos ante fallos en el sistema notificar de la manera más adecuada a los usuarios para evitar que se alarmen ante estas situaciones,
además de mostrar ayudas que faciliten la comprensión de la interfaz de usuario cuando se la encuentran por primera vez.

* Rendimiento

Una vez se consiga una aplicación bonita a ojos del usuario y sin errores graves en funcionamiento buscaremos la mayor velocidad posible en la ejecución
de las distintas opciones que nuestra aplicación ofrezca. No estamos seguros si en el tiempo que disponemos para el 
proyecto conseguiremos maximizar la optimización del mismo.

* Seguridad

La principal arma para la seguridad se basa en lo más principal de este proyecto que consiste en que cada usuario sea dueño de sus datos
al estar contenidos en el POD personal de cada uno. Aún así existen riesgos de ataques como por ejemplo Man in the middle, que si nos sobra tiempo
intentaremos encontrar la manera de solventar.


