language: node_js
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - npm install --save howler
script: 
  - ng build --prod
  - ng e2e
after_success:
  - bash <(curl -s https://codecov.io/bash)