language: node_js
node_js:
  - "10.15"
before_script:
  - npm install -g @angular/cli
  - npm install --save howler
script: 
  - ng build --prod
after_success:
  - node_modules\.bin\cucumber-js src\test\asw\features -r src\test\asw\steps
  - bash <(curl -s https://codecov.io/bash)
