[[section-introduction-and-goals]]
== Introducción y metas



Nos hemos propuesto desarrollar un chat descentralizado, siguiendo las caracteristicas de SOLID.
Buscaremos desarrollar el proyecto para que tenga un sistema con una arquitectura descentralizada, que separe el amacenamiento de datos de la aplicación que estamos desarrollando. También, tenemos como objetivo que los usuarios puedan almacenar los datos de sus chats en sus pods.
Los usuarios de la aplicación, pueden enviarse fotos, vídeos u otros archivos para comunicarse con sus amigos, u otras personas a través del chat. Estas conversaciones, van a poder ser realizadas de manera individual, o de manera grupal, en la que estén incluidos varios participantes.
Un usuario de la aplicación, recibirá las notificaciones de la aplicación, cuando otro usuario o usuarios quieran comunicarse con él.

La aplicación, está pensada para todas aquellas personas que quieran mantener conversaciones sin que esa información quede almacenada en los servidores de la empresa proveedora de la aplicación.  


=== Vista de requisitos

.Funcionales
* Los usuarios que utilicen la aplicación deberán de poseer un pod de SOLID.
* El sistema deberá de notificar al usuario los mensajes que éste reciba.
* El sistema guardará los mensajes encriptados (no en texto plano) en el pod del usuario correspondiente.
* Para recibir los mensajes los usuarios deberán de estar conectados y autentificados en SOLID.

.No funcionales
* Facilidad de aprendizaje para interaccionar con la aplicación por parte de los usuarios novatos en un corto espacio de tiempo.
* El usuario pueda utilizar la aplicación con un tiempo de envío de mensajes óptimo (especificar en versiones posteriores).
* No poseer de una base central de datos, que comprometa la información de los usuarios que la usen.
* Buscar la seguridad, sin tener puntos vulnerables:
** SQL Injection.
** Command Injection.
** Fuga de información.
** Puertas traseras.
** Man in the middle.
** Cross-site request forgery.
** Mensajes encriptados utilizando el algoritmo de encriptación MD5/SHA1Sum.
* Nivel de accesibilidad y usabilidad siguiendo las recomendaciones de w3c.


=== Atributos de calidad

* *Accesibilidad*: diseño de una aplicación accesible para personas con discapacidades 
* *Disponibilidad*: diseño de una aplicación que asegure un cierto grado absoluto de continuidad operacional durante un periodo de duración dado.
* *Modificabilidad*: diseño de una aplicación con un software mantenible en el tiempo.
* *Rendimiento*: capacidad del sistema a realizar operaciones sin un uso excesivo de recursos (memoria, datos, etc).
* *Seguridad*: diseño de una aplicación que no sea vulnerable a:
** SQL Injection.
** Comand Injection.
** Fuga de información.
** Puertas traseras.
** Man in the middle.
** Cross-site request forgery.
* *Testeabilidad*: diseño de una aplicación que sea capaz de pasar un software mínimo de pruebas para comprobar el correcto funcionamiento de esta.
* *Usabilidad*: diseño de una aplicación que sea fácil de usar por parte de los usuarios que interactúen con ella.
* *Escalabilidad*: capacidad de la apliación para albergar un mayor volumen de datos.
* *Interoperabilidad*: capacidad de la aplicación para interactuar y coexistir con otros sistemas.
* *Portabilidad*: característica que posee un software para ejecutarse en diferentes plataformas.
* *Integridad*: diseño de una aplicación que mantenga la información exacta a como fue generada sin ser editada por usuarios o procesos no autizados a ello.
* *Consistencia*: diseño de una aplicación que mantenga sus datos correctos en todo momento.
* *Robustez*: capacidad de la aplicación para actuar y sobreponerse a errores no esperados en tiempo de ejecución.
* *Modular*: diseño de una aplicación mediante subdivisiones de esta, independientes unas de otras.
* *Trazable*: capacidad de la aplicación a seguir el rastro a las actividades realizadas en ella en todas las etapas de su ciclo de vida.

[options="header",cols="2*"]
.Prioridad de los atributos de calidad en el proyecto
|===
|Prioridad | Atributo
| 1 | Disponibilidad
| 2 | Seguridad
| 3 | Consistencia
| 4 | Robustez
| 5 | Integridad
| 6 | Modificabilidad
| 7 | Accesibilidad
| 8 | Usabilidad
| 9 | Trazable
| 10 | Rendimiento
| 11 | Testeabilidad
| 12 | Modular
| 13 | Escalabilidad
| 14 | Interoperabilidad
| 15 | Portabilidad
|===



=== Stakeholders

.Stakeholders
[options="header",cols="2*"]
|===
|Role/Name|Expectations
| Profesorado de la asignatura | Seguir un proceso de desarrollo de la aplicación de acuerdo a lo visto en la asignatura, así como un correcto diseño y arquitectura del producto final.
| SOLID | Realizar un chat descentralizado de acuerdo a la tecnología SOLID.
| Equipo de desarrollo | Realizar el trabajo asignado siguiendo los requisitos establecidos en la documentación siguiendo una metodología ágil de acuerdo a lo aprendido en la asignatura.
|===
